import pandas as pd
import numpy as np

DATA_SCHEMA = {
    'gbifid': 'int64',
    'institutionid': 'str',
    'basisofrecord': 'str',
    'catalognumber': 'str',
    'recordnumber': 'str',
    'recordnumber_contains_numerals': 'bool',
    'recordnumber_contains_year': 'bool',
    'recordedby': 'str',
    'recordedby_has_personal_name': 'bool',
    'recordedbyid': 'str',
    'georeferenceverificationstatus': 'str',
    'othercatalognumbers': 'str',
    'fieldnumber': 'str',
    'fieldnumber_contains_numerals': 'bool',
    'eventdate': 'str',
    'eventdate_day_offset': 'int64',
    'year': 'int64',
    'month': 'int64',
    'day': 'int64',
    'verbatimeventdate': 'str',
    'habitat': 'str',
    'fieldnotes': 'str',
    'eventremarks': 'str',
    'countrycode': 'str',
    'locality': 'str',
    'verbatimlocality': 'str',
    'decimallatitude': 'float64',
    'decimallongitude': 'float64',
    'scientificname': 'str',
    'datasetkey': 'str',
    'elevation': 'float64',
    'elevationaccuracy': 'float64',
    'nontaxonomicissue': 'str',
    'mediatype': 'str',
    'v_associatedmedia': 'str',
    'hascoordinate': 'bool',
    'hasgeospatialissues': 'bool',
    'issequenced': 'bool',
    'institutionkey': 'str',
    'collectionkey': 'str',
    'isincluster': 'bool',
    'recordnumber_mainnumber': 'str',
    'recordedby_first_familyname': 'str',
    'recordedby_team_familynames': 'str',
    'eventdate_eligible': 'bool',
    'recordnumber_eligible': 'bool',
    'recordedby_eligible': 'bool',
    'cluster_stage1_id': 'str',
    'coordinate_source_specimen_metadata': 'str',
    'coordinate_source_collecting_event': 'str',
    'coordinate_source_collector_day': 'str',
    'coordinate_source': 'str',

    'num_records':'int64',
    'recordedby_unique':'int64',
    'recordnumber_unique':'int64',
    'eventdate_unique':'int64',
    'eventdate_day_offset_min':'int64',
    'eventdate_day_offset_max':'int64',
    'year_min':'int64',
    'year_max':'int64',
    'countrycode_unique':'int64',
    'duration_days':'int64',
    'hascoordinate_count':'int64',
    'hascoordinate_pct':'float64',
    'days_active_pct':'float64',
    'itinerary':'str',
    'collecting_areas':'str',
    'placenames':'str',
    'regional_units':'str',

    }