name: Makefile CI

on:
  workflow_dispatch:
  push:
    tags:        
      - v*.**
      
jobs:
      
  build:

    runs-on: ubuntu-latest

    env:
      GBIF_DOWNLOAD_ID: ${{ vars.GBIF_DOWNLOAD_ID }}
      GBIF_DOWNLOAD_COUNTRYCODE: ${{ vars.GBIF_DOWNLOAD_COUNTRYCODE }}
      DWCAGENT_REPO: https://github.com/bionomia/dwc_agent_golang
      DWCAGENT_REF: main
      DWCAGENT_PORT: "7654"

    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.22.x'
        cache: false

    - name: Run cluster build
      run: make all USE_LOCAL_RECORDEDBY_PARSE=true

    - name: Attach built artifacts to run
      if: ${{ github.event_name == 'workflow_dispatch'}}
      uses: actions/upload-artifact@v7
      with:
        name: occurrences-${{ env.GBIF_DOWNLOAD_COUNTRYCODE }}
        path: |
          data/occurrences-${{ env.GBIF_DOWNLOAD_COUNTRYCODE }}-*.tsv
          data/citation.json

